In [1]:
import numpy as np

In [2]:
from sklearn import datasets
E, F = datasets.load_iris(return_X_y= True)

In [3]:
from sklearn.preprocessing import MinMaxScaler
Scale = MinMaxScaler()
Scaled = Scale.fit_transform(E)


In [4]:
split = (0.8,0.2)
seed = 45


rng = np.random.default_rng(seed)

cuts = (np.array(split) * len(E)).astype(int)
i_train, i_val = np.split(rng.permutation(len(E)), cuts[:-1])

x_train, y_train = Scaled[i_train], F[i_train]
x_val, y_val = Scaled[i_val], F[i_val]

In [5]:
from rlvq import RLVQ

In [6]:
trained_model = RLVQ(num_prototypes_per_class=1, initialization_type='random')

In [7]:
trained_model.fit(x_train, y_train)

(array([[0.20508397, 0.61558256, 0.07659336, 0.05774307],
        [0.46849829, 0.33429067, 0.53378738, 0.47781097],
        [0.67346537, 0.43896126, 0.80002282, 0.82734995]]),
 array([0, 1, 2]),
 array([1.87089483e-05, 6.97390696e-05, 6.24510337e-01, 3.75401215e-01]))

In [8]:
#evaluatte on test set
trained_model.evaluate(x_val, y_val)

96.66666666666667

In [9]:
# some_file.py
import sys
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, '/Attacks')



In [10]:
from Attacks.boundaryattack import BoundaryAttack

In [11]:
att = BoundaryAttack(trained_model)

In [12]:
att.fit(x_val, y_val)

In [13]:
att.boundary_attack(x_val[2])

Step #0...
	Delta step...
	#1
20
1.0
	Epsilon step...
	#1
	#2
	#3
	#4
	#5
1 steps
0.5620839436310131 diff
Step #1...
	Delta step...
	#1
20
1.0
	Epsilon step...
	#1
	#2
	#3
	#4
	#5
Step #2...
	Delta step...
	#1
20
0.0
	#2
20
0.0
	#3
20
0.0
	#4
20
0.0
	#5
20
0.0
	#6
20
0.0
	#7
20
0.0
	#8
20
0.0
	#9
20
0.0
	#10
20
0.0
	#11
20
0.0
	#12
20
0.0
	#13
20
0.0
	#14
20
0.0
	#15
20
0.0
	#16
20
0.0
	#17
20
0.0
	#18
20
0.0
	#19
20
0.0
	#20
20
0.0
	#21
20
0.0
	#22
20
0.0
	#23
20
0.0
	#24
20
0.0
	#25
20
0.0
	#26
20
0.0
	#27
20
1.0
	Epsilon step...
	#1
	#2
	#3
	#4
	#5
	#6
	#7
Step #3...
	Delta step...
	#1
20
0.0
	#2
20
0.0
	#3
20
0.0
	#4
20
0.0
	#5
20
0.0
	#6
20
0.0
	#7
20
0.0
	#8
20
0.0
	#9
20
0.0
	#10
20
0.0
	#11
20
0.0
	#12
20
0.0
	#13
20
0.0
	#14
20
0.0
	#15
20
0.0
	#16
20
0.0
	#17
20
0.0
	#18
20
0.0
	#19
20
0.0
	#20
20
0.0
	#21
20
0.0
	#22
20
0.0
	#23
20
0.0
	#24
20
0.0
	#25
20
0.0
	#26
20
0.0
	#27
20
0.0
	#28
20
0.0
	#29
20
0.0
	#30
20
0.0
	#31
20
1.0
	Epsilon step...
	#1
	#2
	#3
	#4
	#5
	#6
Step

20
0.0
	#7
20
0.0
	#8
20
0.0
	#9
20
0.0
	#10
20
0.0
	#11
20
0.0
	#12
20
0.0
	#13
20
0.0
	#14
20
0.0
	#15
20
0.0
	#16
20
0.0
	#17
20
0.0
	#18
20
0.0
	#19
20
0.0
	#20
20
0.0
	#21
20
0.0
	#22
20
0.0
	#23
20
0.0
	#24
20
0.0
	#25
20
0.0
	#26
20
0.0
	#27
20
0.0
	#28
20
0.0
	#29
20
0.0
	#30
20
0.0
	#31
20
0.0
	#32
20
0.0
	#33
20
0.0
	#34
20
0.0
	#35
20
0.0
	#36
20
0.0
	#37
20
0.0
	#38
20
0.0
	#39
20
0.0
	#40
20
1.0
	Epsilon step...
	#1
	#2
	#3
	#4
	#5
	#6
5 steps
0.5591488704048452 diff
Step #5...
	Delta step...
	#1
20
0.0
	#2
20
0.0
	#3
20
1.0
	Epsilon step...
	#1
	#2
	#3
	#4
Step #6...
	Delta step...
	#1
20
0.0
	#2
20
0.0
	#3
20
0.0
	#4
20
0.0
	#5
20
0.0
	#6
20
0.0
	#7
20
0.0
	#8
20
0.0
	#9
20
0.0
	#10
20
0.0
	#11
20
0.0
	#12
20
0.0
	#13
20
0.0
	#14
20
0.0
	#15
20
0.0
	#16
20
0.0
	#17
20
0.0
	#18
20
0.0
	#19
20
0.0
	#20
20
0.0
	#21
20
0.0
	#22
20
0.0
	#23
20
0.0
	#24
20
0.0
	#25
20
0.0
	#26
20
0.0
	#27
20
0.0
	#28
20
0.0
	#29
20
0.0
	#30
20
0.0
	#31
20
0.0
	#32
20
0.0
	#33
20
0.0
	#34
20
0.

(array([0.3313939 , 0.54305556, 0.35372738, 0.2639495 ]), 0.559148510887955, 0)

In [14]:
y_val

array([0, 1, 2, 2, 0, 2, 2, 2, 0, 1, 2, 0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0,
       0, 2, 2, 1, 0, 1, 0, 0])